/*
MIT License
Copyright (c) 2019 
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
namespace ProfanityFilter
{
    /// <summary>
    /// This class contains the profanity list.
    ///
    /// WARNING : This file contains a lot of very offensive terminology. Do not read the content of this source code
    /// file if you are easily offended.
    /// </summary>
    public partial class ProfanityBase
    {
        private readonly string[] _wordList =
        {
            "\b2 girls 1 cup\b",
            "\b2 girls one cup\b",
            "\b2g1c\b",
            "\b4r5e\b",
            "\b5h1t\b",
            "\b5hit\b",
            "\b8===D\b",
            "\b8==D\b",
            "\b8=D\b",
            "\ba$$\b",
            "\ba$$hole\b",
            "\ba_s_s\b",
            "\ba2m\b",
            "\ba55\b",
            "\ba55hole\b",
            "\bacrotomophilia\b",
            "\baeolus\b",
            "\bahole\b",
            "\balabama hot pocket\b",
            "\balaskan pipeline\b",
            "\banal\b",
            "\banal impaler\b",
            "\banal leakage\b",
            "\banalprobe\b",
            "\banilingus\b",
            "\bangrydragon\b",
            "\bangry dragon\b",
            "\banus\b",
            "\bapeshit\b",
            "\bar5e\b",
            "\barian\b",
            "\barrse\b",
            "\barse\b",
            "\barses\b",
            "\barsehole\b",
            "\baryan\b",
            "\bass\b",
            "\bass fuck\b",
            "\bass hole\b",
            "\bassbag\b",
            "\bassbandit\b",
            "\bassbang\b",
            "\bassbanged\b",
            "\bassbanger\b",
            "\bassbangs\b",
            "\bassbite\b",
            "\bassclown\b",
            "\basscock\b",
            "\basscracker\b",
            "\basses\b",
            "\bassface\b",
            "\bassfaces\b",
            "\bassfuck\b",
            "\bassfucker\b",
            "\bass-fucker\b",
            "\bassfukka\b",
            "\bassgoblin\b",
            "\bassh0le\b",
            "\basshat\b",
            "\bass-hat\b",
            "\basshead\b",
            "\bassho1e\b",
            "\basshole\b",
            "\bassholes\b",
            "\basshopper\b",
            "\bass-jabber\b",
            "\bassjacker\b",
            "\basslick\b",
            "\basslicker\b",
            "\bassmaster\b",
            "\bassmonkey\b",
            "\bassmucus\b",
            "\bassmunch\b",
            "\bassmuncher\b",
            "\bassnigger\b",
            "\basspirate\b",
            "\bass-pirate\b",
            "\bassshit\b",
            "\bassshole\b",
            "\basssucker\b",
            "\basswad\b",
            "\basswhole\b",
            "\basswipe\b",
            "\basswipes\b",
            "\bauto erotic\b",
            "\bautoerotic\b",
            "\baxwound\b",
            "\baxewound\b",
            "\baxe wound\b",
            "\bazazel\b",
            "\bazz\b",
            "\bb!tch\b",
            "\bb00bs\b",
            "\bb17ch\b",
            "\bb1tch\b",
            "\bbabeland\b",
            "\bbaby batter\b",
            "\bbaby juice\b",
            "\bball gag\b",
            "\bball gravy\b",
            "\bball kicking\b",
            "\bball licking\b",
            "\bball sack\b",
            "\bball sucking\b",
            "\bballbag\b",
            "\bballs\b",
            "\bballsack\b",
            "\bbampot\b",
            "\bbang (one's) box\b",
            "\bbangbros\b",
            "\bbareback\b",
            "\bbarely legal\b",
            "\bbarenaked\b",
            "\bbarf\b",
            "\bbastard\b",
            "\bbastardo\b",
            "\bbastards\b",
            "\bbastinado\b",
            "\bbatty boy\b",
            "\bbawdy\b",
            "\bbbw\b",
            "\bbdsm\b",
            "\bbeaner\b",
            "\bbeaners\b",
            "\bbeardedclam\b",
            "\bbeastial\b",
            "\bbeastiality\b",
            "\bbeatch\b",
            "\bbeaver\b",
            "\bbeaver cleaver\b",
            "\bbeaver lips\b",
            "\bbeef curtain\b",
            "\bbeef curtains\b",
            "\bbeeyotch\b",
            "\bbellend\b",
            "\bbender\b",
            "\bbeotch\b",
            "\bbescumber\b",
            "\bbestial\b",
            "\bbestiality\b",
            "\bbi+ch\b",
            "\bbiatch\b",
            "\bbig black\b",
            "\bbig breasts\b",
            "\bbig knockers\b",
            "\bbig tits\b",
            "\bbigtits\b",
            "\bbimbo\b",
            "\bbimbos\b",
            "\bbint\b",
            "\bbirdlock\b",
            "\bbitch\b",
            "\bbitch tit\b",
            "\bbitchass\b",
            "\bbitched\b",
            "\bbitcher\b",
            "\bbitchers\b",
            "\bbitches\b",
            "\bbitchin\b",
            "\bbitching\b",
            "\bbitchtits\b",
            "\bbitchy\b",
            "\bblack cock\b",
            "\bblonde action\b",
            "\bblonde on blonde action\b",
            "\bbloodclaat\b",
            "\bbloody\b",
            "\bbloody hell\b",
            "\bblow job\b",
            "\bblow me\b",
            "\bblow mud\b",
            "\bblow your load\b",
            "\bblowjob\b",
            "\bblowjobs\b",
            "\bblue waffle\b",
            "\bblumpkin\b",
            "\bbod\b",
            "\bbodily\b",
            "\bboink\b",
            "\bboiolas\b",
            "\bbollock\b",
            "\bbollocks\b",
            "\bbollok\b",
            "\bbollox\b",
            "\bbondage\b",
            "\bboned\b",
            "\bboner\b",
            "\bboners\b",
            "\bbong\b",
            "\bboob\b",
            "\bboobies\b",
            "\bboobs\b",
            "\bbooby\b",
            "\bbooger\b",
            "\bbookie\b",
            "\bboong\b",
            "\bbooobs\b",
            "\bboooobs\b",
            "\bbooooobs\b",
            "\bbooooooobs\b",
            "\bbootee\b",
            "\bbootie\b",
            "\bbooty\b",
            "\bbooty call\b",
            "\bbooze\b",
            "\bboozer\b",
            "\bboozy\b",
            "\bbosom\b",
            "\bbosomy\b",
            "\bbreasts\b",
            "\bbreeder\b",
            "\bbrotherfucker\b",
            "\bbrown showers\b",
            "\bbrunette action\b",
            "\bbuceta\b",
            "\bbugger\b",
            "\bbukkake\b",
            "\bbull shit\b",
            "\bbulldyke\b",
            "\bbullet vibe\b",
            "\bbullshit\b",
            "\bbullshits\b",
            "\bbullshitted\b",
            "\bbullturds\b",
            "\bbum\b",
            "\bbum boy\b",
            "\bbumblefuck\b",
            "\bbumclat\b",
            "\bbummer\b",
            "\bbuncombe\b",
            "\bbung\b",
            "\bbung hole\b",
            "\bbunghole\b",
            "\bbunny fucker\b",
            "\bbust a load\b",
            "\bbusty\b",
            "\bbutt\b",
            "\bbutt fuck\b",
            "\bbutt plug\b",
            "\bbuttcheeks\b",
            "\bbuttfuck\b",
            "\bbuttfucka\b",
            "\bbuttfucker\b",
            "\bbutthole\b",
            "\bbuttmuch\b",
            "\bbuttmunch\b",
            "\bbutt-pirate\b",
            "\bbuttplug\b",
            "\bc.0.c.k\b",
            "\bc.o.c.k.\b",
            "\bc.u.n.t\b",
            "\bc0ck\b",
            "\bc-0-c-k\b",
            "\bc0cksucker\b",
            "\bcaca\b",
            "\bcacafuego\b",
            "\bcahone\b",
            "\bcamel toe\b",
            "\bcameltoe\b",
            "\bcamgirl\b",
            "\bcamslut\b",
            "\bcamwhore\b",
            "\bcarpet muncher\b",
            "\bcarpetmuncher\b",
            "\bcawk\b",
            "\bcervix\b",
            "\bchesticle\b",
            "\bchi-chi man\b",
            "\bchick with a dick\b",
            "\bchild-fucker\b",
            "\bchinc\b",
            "\bchincs\b",
            "\bchink\b",
            "\bchinky\b",
            "\bchoad\b",
            "\bchoade\b",
            "\bchoc ice\b",
            "\bchocolate rosebuds\b",
            "\bchode\b",
            "\bchodes\b",
            "\bchota bags\b",
            "\bcipa\b",
            "\bcirclejerk\b",
            "\bcl1t\b",
            "\bcleveland steamer\b",
            "\bclimax\b",
            "\bclit\b",
            "\bclit licker\b",
            "\bclitface\b",
            "\bclitfuck\b",
            "\bclitoris\b",
            "\bclits\b",
            "\bclitty\b",
            "\bclitty litter\b",
            "\bclover clamps\b",
            "\bclunge\b",
            "\bclusterfuck\b",
            "\bcnut\b",
            "\bcocain\b",
            "\bcocaine\b",
            "\bcoccydynia\b",
            "\bcock\b",
            "\bc-o-c-k\b",
            "\bcock pocket\b",
            "\bcock snot\b",
            "\bcock sucker\b",
            "\bcockass\b",
            "\bcockbite\b",
            "\bcockblock\b",
            "\bcockburger\b",
            "\bcockeye\b",
            "\bcockface\b",
            "\bcockfucker\b",
            "\bcockhead\b",
            "\bcockholster\b",
            "\bcockjockey\b",
            "\bcockknocker\b",
            "\bcockknoker\b",
            "\bcocklump\b",
            "\bcockmaster\b",
            "\bcockmongler\b",
            "\bcockmongruel\b",
            "\bcockmonkey\b",
            "\bcockmunch\b",
            "\bcockmuncher\b",
            "\bcocknose\b",
            "\bcocknugget\b",
            "\bcocks\b",
            "\bcockshit\b",
            "\bcocksmith\b",
            "\bcocksmoke\b",
            "\bcocksmoker\b",
            "\bcocksniffer\b",
            "\bcocksuck\b",
            "\bcocksucked\b",
            "\bcocksucker\b",
            "\bcock-sucker\b",
            "\bcocksuckers\b",
            "\bcocksucking\b",
            "\bcocksucks\b",
            "\bcocksuka\b",
            "\bcocksukka\b",
            "\bcockwaffle\b",
            "\bcoffin dodger\b",
            "\bcoital\b",
            "\bcok\b",
            "\bcokmuncher\b",
            "\bcoksucka\b",
            "\bcommie\b",
            "\bcondom\b",
            "\bcoochie\b",
            "\bcoochy\b",
            "\bcoon\b",
            "\bcoonnass\b",
            "\bcoons\b",
            "\bcooter\b",
            "\bcop some wood\b",
            "\bcoprolagnia\b",
            "\bcoprophilia\b",
            "\bcorksucker\b",
            "\bcornhole\b",
            "\bcorp whore\b",
            "\bcorpulent\b",
            "\bcox\b",
            "\bcrabs\b",
            "\bcrack\b",
            "\bcracker\b",
            "\bcrackwhore\b",
            "\bcrap\b",
            "\bcrappy\b",
            "\bcreampie\b",
            "\bcretin\b",
            "\bcrikey\b",
            "\bcripple\b",
            "\bcrotte\b",
            "\bcum\b",
            "\bcum chugger\b",
            "\bcum dumpster\b",
            "\bcum freak\b",
            "\bcum guzzler\b",
            "\bcumbubble\b",
            "\bcumdump\b",
            "\bcumdumpster\b",
            "\bcumguzzler\b",
            "\bcumjockey\b",
            "\bcummer\b",
            "\bcummin\b",
            "\bcumming\b",
            "\bcums\b",
            "\bcumshot\b",
            "\bcumshots\b",
            "\bcumslut\b",
            "\bcumstain\b",
            "\bcumtart\b",
            "\bcunilingus\b",
            "\bcunillingus\b",
            "\bcunnie\b",
            "\bcunnilingus\b",
            "\bcunny\b",
            "\bcunt\b",
            "\bc-u-n-t\b",
            "\bcunt hair\b",
            "\bcuntass\b",
            "\bcuntbag\b",
            "\bcuntface\b",
            "\bcunthole\b",
            "\bcunthunter\b",
            "\bcuntlick\b",
            "\bcuntlicker\b",
            "\bcuntrag\b",
            "\bcunts\b",
            "\bcuntsicle\b",
            "\bcuntslut\b",
            "\bcunt-struck\b",
            "\bcus\b",
            "\bcut rope\b",
            "\bcyalis\b",
            "\bcyberfuc\b",
            "\bcyberfuck\b",
            "\bcyberfucked\b",
            "\bcyberfucker\b",
            "\bcyberfucking\b",
            "\bd0ng\b",
            "\bd0uch3\b",
            "\bd0uche\b",
            "\bd1ck\b",
            "\bd1ld0\b",
            "\bd1ldo\b",
            "\bdago\b",
            "\bdagos\b",
            "\bdammit\b",
            "\bdamn\b",
            "\bdamned\b",
            "\bdamnit\b",
            "\bdarkie\b",
            "\bdarn\b",
            "\bdate rape\b",
            "\bdaterape\b",
            "\bdawgie-style\b",
            "\bdeep throat\b",
            "\bdeepthroat\b",
            "\bdeggo\b",
            "\bdendrophilia\b",
            "\bdick\b",
            "\bdick head\b",
            "\bdick hole\b",
            "\bdick shy\b",
            "\bdickbag\b",
            "\bdickbeaters\b",
            "\bdickdipper\b",
            "\bdickface\b",
            "\bdickflipper\b",
            "\bdickfuck\b",
            "\bdickfucker\b",
            "\bdickhead\b",
            "\bdickheads\b",
            "\bdickhole\b",
            "\bdickish\b",
            "\bdick-ish\b",
            "\bdickjuice\b",
            "\bdickmilk\b",
            "\bdickmonger\b",
            "\bdickripper\b",
            "\bdicks\b",
            "\bdicksipper\b",
            "\bdickslap\b",
            "\bdick-sneeze\b",
            "\bdicksucker\b",
            "\bdicksucking\b",
            "\bdicktickler\b",
            "\bdickwad\b",
            "\bdickweasel\b",
            "\bdickweed\b",
            "\bdickwhipper\b",
            "\bdickwod\b",
            "\bdickzipper\b",
            "\bdiddle\b",
            "\bdike\b",
            "\bdildo\b",
            "\bdildos\b",
            "\bdiligaf\b",
            "\bdillweed\b",
            "\bdimwit\b",
            "\bdingle\b",
            "\bdingleberries\b",
            "\bdingleberry\b",
            "\bdink\b",
            "\bdinks\b",
            "\bdipship\b",
            "\bdirsa\b",
            "\bdirty\b",
            "\bdirty pillows\b",
            "\bdirty sanchez\b",
            "\bdiv\b",
            "\bdlck\b",
            "\bdog style\b",
            "\bdog-fucker\b",
            "\bdoggie style\b",
            "\bdoggiestyle\b",
            "\bdoggie-style\b",
            "\bdoggin\b",
            "\bdogging\b",
            "\bdoggy style\b",
            "\bdoggystyle\b",
            "\bdoggy-style\b",
            "\bdolcett\b",
            "\bdomination\b",
            "\bdominatrix\b",
            "\bdommes\b",
            "\bdong\b",
            "\bdonkey punch\b",
            "\bdonkeypunch\b",
            "\bdonkeyribber\b",
            "\bdoochbag\b",
            "\bdoofus\b",
            "\bdookie\b",
            "\bdoosh\b",
            "\bdopey\b",
            "\bdouble dong\b",
            "\bdouble penetration\b",
            "\bdoublelift\b",
            "\bdouch3\b",
            "\bdouche\b",
            "\bdouchebag\b",
            "\bdouchebags\b",
            "\bdouche-fag\b",
            "\bdouchewaffle\b",
            "\bdouchey\b",
            "\bdp action\b",
            "\bdrunk\b",
            "\bdry hump\b",
            "\bduche\b",
            "\bdumass\b",
            "\bdumb ass\b",
            "\bdumbass\b",
            "\bdumbasses\b",
            "\bdumbcunt\b",
            "\bdumbfuck\b",
            "\bdumbshit\b",
            "\bdummy\b",
            "\bdumshit\b",
            "\bdvda\b",
            "\bdyke\b",
            "\bdykes\b",
            "\beat a dick\b",
            "\beat hair pie\b",
            "\beat my ass\b",
            "\becchi\b",
            "\bejaculate\b",
            "\bejaculated\b",
            "\bejaculates\b",
            "\bejaculating\b",
            "\bejaculatings\b",
            "\bejaculation\b",
            "\bejakulate\b",
            "\berect\b",
            "\berection\b",
            "\berotic\b",
            "\berotism\b",
            "\bescort\b",
            "\bessohbee\b",
            "\beunuch\b",
            "\bextacy\b",
            "\bextasy\b",
            "\bf u c k\b",
            "\bf u c k e r\b",
            "\bf.u.c.k\b",
            "\bf_u_c_k\b",
            "\bf4nny\b",
            "\bfacial\b",
            "\bfack\b",
            "\bfag\b",
            "\bfagbag\b",
            "\bfagfucker\b",
            "\bfagg\b",
            "\bfagged\b",
            "\bfagging\b",
            "\bfaggit\b",
            "\bfaggitt\b",
            "\bfaggot\b",
            "\bfaggotcock\b",
            "\bfaggots\b",
            "\bfaggs\b",
            "\bfagot\b",
            "\bfagots\b",
            "\bfags\b",
            "\bfagtard\b",
            "\bfaig\b",
            "\bfaigt\b",
            "\bfanny\b",
            "\bfannybandit\b",
            "\bfannyflaps\b",
            "\bfannyfucker\b",
            "\bfanyy\b",
            "\bfart\b",
            "\bfartknocker\b",
            "\bfatass\b",
            "\bfcuk\b",
            "\bfcuker\b",
            "\bfcuking\b",
            "\bfecal\b",
            "\bfeck\b",
            "\bfecker\b",
            "\bfeist\b",
            "\bfelch\b",
            "\bfelcher\b",
            "\bfelching\b",
            "\bfellate\b",
            "\bfellatio\b",
            "\bfeltch\b",
            "\bfeltcher\b",
            "\bfemale squirting\b",
            "\bfemdom\b",
            "\bfenian\b",
            "\bfice\b",
            "\bfigging\b",
            "\bfingerbang\b",
            "\bfingerfuck\b",
            "\bfingerfucked\b",
            "\bfingerfucker\b",
            "\bfingerfuckers\b",
            "\bfingerfucking\b",
            "\bfingerfucks\b",
            "\bfingering\b",
            "\bfist fuck\b",
            "\bfisted\b",
            "\bfistfuck\b",
            "\bfistfucked\b",
            "\bfistfucker\b",
            "\bfistfuckers\b",
            "\bfistfuckings\b",
            "\bfistfucks\b",
            "\bfisting\b",
            "\bfisty\b",
            "\bflamer\b",
            "\bflange\b",
            "\bflaps\b",
            "\bfleshflute\b",
            "\bflog the log\b",
            "\bfloozy\b",
            "\bfoad\b",
            "\bfoah\b",
            "\bfondle\b",
            "\bfoobar\b",
            "\bfook\b",
            "\bfooker\b",
            "\bfoot fetish\b",
            "\bfootjob\b",
            "\bforeskin\b",
            "\bfreex\b",
            "\bfrenchify\b",
            "\bfrigg\b",
            "\bfrigga\b",
            "\bfrotting\b",
            "\bfubar\b",
            "\bfuc\b",
            "\bfuck\b",
            "\bf-u-c-k\b",
            "\bfuck buttons\b",
            "\bfuck hole\b",
            "\bfuck off\b",
            "\bfuck puppet\b",
            "\bfuck trophy\b",
            "\bfuck yo mama\b",
            "\bfuck you\b",
            "\bfucka\b",
            "\bfuckass\b",
            "\bfuck-ass\b",
            "\bfuckbag\b",
            "\bfuck bag\b",
            "\bfuck-bitch\b",
            "\bfuckboy\b",
            "\bfuckbrain\b",
            "\bfuckbutt\b",
            "\bfuckbutter\b",
            "\bfucked\b",
            "\bfuckedup\b",
            "\bfucked up\b",
            "\bfucker\b",
            "\bfuckers\b",
            "\bfuckersucker\b",
            "\bfuckface\b",
            "\bfuckhead\b",
            "\bfuckheads\b",
            "\bfuckhole\b",
            "\bfuckin\b",
            "\bfucking\b",
            "\bfuckings\b",
            "\bfuckme\b",
            "\bfuck me\b",
            "\bfuckmeat\b",
            "\bfucknugget\b",
            "\bfucknut\b",
            "\bfucknutt\b",
            "\bfuckoff\b",
            "\bfucks\b",
            "\bfuckstick\b",
            "\bfucktard\b",
            "\bfuck-tard\b",
            "\bfucktards\b",
            "\bfucktart\b",
            "\bfucktoy\b",
            "\bfucktwat\b",
            "\bfuckup\b",
            "\bfuckwad\b",
            "\bfuckwhit\b",
            "\bfuckwit\b",
            "\bfuckwitt\b",
            "\bfudge packer\b",
            "\bfudgepacker\b",
            "\bfudge-packer\b",
            "\bfuk\b",
            "\bfuker\b",
            "\bfukker\b",
            "\bfukkers\b",
            "\bfukkin\b",
            "\bfuks\b",
            "\bfukwhit\b",
            "\bfukwit\b",
            "\bfuq\b",
            "\bfutanari\b",
            "\bfux\b",
            "\bfux0r\b",
            "\bfvck\b",
            "\bfxck\b",
            "\bgae\b",
            "\bgai\b",
            "\bgang bang\b",
            "\bgangbang\b",
            "\bgang-bang\b",
            "\bgangbanged\b",
            "\bgangbangs\b",
            "\bganja\b",
            "\bgash\b",
            "\bgassy ass\b",
            "\bgay sex\b",
            "\bgayass\b",
            "\bgaybob\b",
            "\bgaydo\b",
            "\bgayfuck\b",
            "\bgayfuckist\b",
            "\bgaylord\b",
            "\bgays\b",
            "\bgaysex\b",
            "\bgaytard\b",
            "\bgaywad\b",
            "\bgender bender\b",
            "\bgenitals\b",
            "\bgey\b",
            "\bgfy\b",
            "\bghay\b",
            "\bghey\b",
            "\bgiant cock\b",
            "\bgigolo\b",
            "\bginger\b",
            "\bgippo\b",
            "\bgirl on\b",
            "\bgirl on top\b",
            "\bgirls gone wild\b",
            "\bglans\b",
            "\bgoatcx\b",
            "\bgoatse\b",
            "\bgod\b",
            "\bgod damn\b",
            "\bgodamn\b",
            "\bgodamnit\b",
            "\bgoddam\b",
            "\bgod-dam\b",
            "\bgoddammit\b",
            "\bgoddamn\b",
            "\bgoddamned\b",
            "\bgod-damned\b",
            "\bgoddamnit\b",
            "\bgodsdamn\b",
            "\bgokkun\b",
            "\bgolden shower\b",
            "\bgoldenshower\b",
            "\bgolliwog\b",
            "\bgonad\b",
            "\bgonads\b",
            "\bgoo girl\b",
            "\bgooch\b",
            "\bgoodpoop\b",
            "\bgook\b",
            "\bgooks\b",
            "\bgoregasm\b",
            "\bgringo\b",
            "\bgrope\b",
            "\bgroup sex\b",
            "\bgspot\b",
            "\bg-spot\b",
            "\bgtfo\b",
            "\bguido\b",
            "\bguro\b",
            "\bh0m0\b",
            "\bh0mo\b",
            "\bham flap\b",
            "\bhand job\b",
            "\bhandjob\b",
            "\bhard core\b",
            "\bhard on\b",
            "\bhardcore\b",
            "\bhardcoresex\b",
            "\bhe11\b",
            "\bhebe\b",
            "\bheeb\b",
            "\bhell\b",
            "\bhemp\b",
            "\bhentai\b",
            "\bheroin\b",
            "\bherp\b",
            "\bherpes\b",
            "\bherpy\b",
            "\bheshe\b",
            "\bhe-she\b",
            "\bhircismus\b",
            "\bhitler\b",
            "\bhiv\b",
            "\bhoar\b",
            "\bhoare\b",
            "\bhobag\b",
            "\bhoe\b",
            "\bhoer\b",
            "\bholy shit\b",
            "\bhom0\b",
            "\bhomey\b",
            "\bhomo\b",
            "\bhomodumbshit\b",
            "\bhomoerotic\b",
            "\bhomoey\b",
            "\bhonkey\b",
            "\bhonky\b",
            "\bhooch\b",
            "\bhookah\b",
            "\bhooker\b",
            "\bhoor\b",
            "\bhootch\b",
            "\bhooter\b",
            "\bhooters\b",
            "\bhore\b",
            "\bhorniest\b",
            "\bhorny\b",
            "\bhot carl\b",
            "\bhot chick\b",
            "\bhotsex\b",
            "\bhow to kill\b",
            "\bhow to murdep\b",
            "\bhow to murder\b",
            "\bhuge fat\b",
            "\bhump\b",
            "\bhumped\b",
            "\bhumping\b",
            "\bhun\b",
            "\bhussy\b",
            "\bhymen\b",
            "\biap\b",
            "\biberian slap\b",
            "\binbred\b",
            "\bincest\b",
            "\binjun\b",
            "\bintercourse\b",
            "\bjack off\b",
            "\bjackass\b",
            "\bjackasses\b",
            "\bjackhole\b",
            "\bjackoff\b",
            "\bjack-off\b",
            "\bjaggi\b",
            "\bjagoff\b",
            "\bjail bait\b",
            "\bjailbait\b",
            "\bjap\b",
            "\bjaps\b",
            "\bjelly donut\b",
            "\bjerk\b",
            "\bjerk off\b",
            "\bjerk0ff\b",
            "\bjerkass\b",
            "\bjerked\b",
            "\bjerkoff\b",
            "\bjerk-off\b",
            "\bjigaboo\b",
            "\bjiggaboo\b",
            "\bjiggerboo\b",
            "\bjism\b",
            "\bjiz\b",
            "\bjizm\b",
            "\bjizz\b",
            "\bjizzed\b",
            "\bjock\b",
            "\bjuggs\b",
            "\bjungle bunny\b",
            "\bjunglebunny\b",
            "\bjunkie\b",
            "\bjunky\b",
            "\bkafir\b",
            "\bkawk\b",
            "\bkike\b",
            "\bkikes\b",
            "\bkill\b",
            "\bkinbaku\b",
            "\bkinkster\b",
            "\bkinky\b",
            "\bklan\b",
            "\bknob\b",
            "\bknob end\b",
            "\bknobbing\b",
            "\bknobead\b",
            "\bknobed\b",
            "\bknobend\b",
            "\bknobhead\b",
            "\bknobjocky\b",
            "\bknobjokey\b",
            "\bkock\b",
            "\bkondum\b",
            "\bkondums\b",
            "\bkooch\b",
            "\bkooches\b",
            "\bkootch\b",
            "\bkraut\b",
            "\bkum\b",
            "\bkummer\b",
            "\bkumming\b",
            "\bkums\b",
            "\bkunilingus\b",
            "\bkunja\b",
            "\bkunt\b",
            "\bkwif\b",
            "\bkyke\b",
            "\bl3i+ch\b",
            "\bl3itch\b",
            "\blabia\b",
            "\blameass\b",
            "\blardass\b",
            "\bleather restraint\b",
            "\bleather straight jacket\b",
            "\blech\b",
            "\blemon party\b",
            "\bLEN\b",
            "\bleper\b",
            "\blesbian\b",
            "\blesbians\b",
            "\blesbo\b",
            "\blesbos\b",
            "\blez\b",
            "\blezza/lesbo\b",
            "\blezzie\b",
            "\blmao\b",
            "\blmfao\b",
            "\bloin\b",
            "\bloins\b",
            "\blolita\b",
            "\blooney\b",
            "\blovemaking\b",
            "\blube\b",
            "\blust\b",
            "\blusting\b",
            "\blusty\b",
            "\bm0f0\b",
            "\bm0fo\b",
            "\bm45terbate\b",
            "\bma5terb8\b",
            "\bma5terbate\b",
            "\bmafugly\b",
            "\bmake me come\b",
            "\bmale squirting\b",
            "\bmams\b",
            "\bmasochist\b",
            "\bmassa\b",
            "\bmasterb8\b",
            "\bmasterbat*\b",
            "\bmasterbat3\b",
            "\bmasterbate\b",
            "\bmaster-bate\b",
            "\bmasterbating\b",
            "\bmasterbation\b",
            "\bmasterbations\b",
            "\bmasturbate\b",
            "\bmasturbating\b",
            "\bmasturbation\b",
            "\bmaxi\b",
            "\bmcfagget\b",
            "\bmenage a trois\b",
            "\bmenses\b",
            "\bmeth\b",
            "\bm-fucking\b",
            "\bmick\b",
            "\bmicrophallus\b",
            "\bmiddle finger\b",
            "\bmidget\b",
            "\bmilf\b",
            "\bminge\b",
            "\bminger\b",
            "\bmissionary position\b",
            "\bmof0\b",
            "\bmofo\b",
            "\bmo-fo\b",
            "\bmolest\b",
            "\bmong\b",
            "\bmoo moo foo foo\b",
            "\bmoolie\b",
            "\bmoron\b",
            "\bmothafuck\b",
            "\bmothafucka\b",
            "\bmothafuckas\b",
            "\bmothafuckaz\b",
            "\bmothafucked\b",
            "\bmothafucker\b",
            "\bmothafuckers\b",
            "\bmothafuckin\b",
            "\bmothafucking\b",
            "\bmothafuckings\b",
            "\bmothafucks\b",
            "\bmother fucker\b",
            "\bmotherfuck\b",
            "\bmotherfucka\b",
            "\bmotherfucked\b",
            "\bmotherfucker\b",
            "\bmotherfuckers\b",
            "\bmotherfuckin\b",
            "\bmotherfucking\b",
            "\bmotherfuckings\b",
            "\bmotherfuckka\b",
            "\bmotherfucks\b",
            "\bmound of venus\b",
            "\bmr hands\b",
            "\bmuff\b",
            "\bmuff diver\b",
            "\bmuff puff\b",
            "\bmuffdiver\b",
            "\bmuffdiving\b",
            "\bmunging\b",
            "\bmunter\b",
            "\bmurder\b",
            "\bmutha\b",
            "\bmuthafecker\b",
            "\bmuthafuckker\b",
            "\bmuther\b",
            "\bmutherfucker\b",
            "\bn1gga\b",
            "\bn1gger\b",
            "\bnaked\b",
            "\bnambla\b",
            "\bnapalm\b",
            "\bnappy\b",
            "\bnawashi\b",
            "\bnazi\b",
            "\bnazism\b",
            "\bneed the dick\b",
            "\bnegro\b",
            "\bneonazi\b",
            "\bnig nog\b",
            "\bnigaboo\b",
            "\bnigg3r\b",
            "\bnigg4h\b",
            "\bnigga\b",
            "\bniggah\b",
            "\bniggas\b",
            "\bniggaz\b",
            "\bnigger\b",
            "\bniggers\b",
            "\bniggle\b",
            "\bniglet\b",
            "\bnig-nog\b",
            "\bnimphomania\b",
            "\bnimrod\b",
            "\bninny\b",
            "\bninnyhammer\b",
            "\bnipple\b",
            "\bnipples\b",
            "\bnob\b",
            "\bnob jokey\b",
            "\bnobhead\b",
            "\bnobjocky\b",
            "\bnobjokey\b",
            "\bnonce\b",
            "\bnsfw images\b",
            "\bnude\b",
            "\bnudity\b",
            "\bnumbnuts\b",
            "\bnut butter\b",
            "\bnut sack\b",
            "\bnutsack\b",
            "\bnutter\b",
            "\bnympho\b",
            "\bnymphomania\b",
            "\boctopussy\b",
            "\bold bag\b",
            "\bomg\b",
            "\bomorashi\b",
            "\bone cup two girls\b",
            "\b1 cup 2 girls\b",
            "\bone cup 2 girls\b",
            "\b1 cup two girls\b",
            "\bone guy one jar\b",
            "\b1 guy one jar\b",
            "\bone guy 1 jar\b",
            "\bopiate\b",
            "\bopium\b",
            "\borally\b",
            "\borgan\b",
            "\borgasim\b",
            "\borgasims\b",
            "\borgasm\b",
            "\borgasmic\b",
            "\borgasms\b",
            "\borgies\b",
            "\borgy\b",
            "\bovary\b",
            "\bovum\b",
            "\bovums\b",
            "\bp.u.s.s.y.\b",
            "\bp.u.s.s.y\b",
            "\bp0rn\b",
            "\bpaedophile\b",
            "\bpaki\b",
            "\bpanooch\b",
            "\bpansy\b",
            "\bpantie\b",
            "\bpanties\b",
            "\bpanty\b",
            "\bpawn\b",
            "\bpcp\b",
            "\bpecker\b",
            "\bpeckerhead\b",
            "\bpedo\b",
            "\bpedobear\b",
            "\bpedophile\b",
            "\bpedophilia\b",
            "\bpedophiliac\b",
            "\bpee\b",
            "\bpeepee\b",
            "\bpegging\b",
            "\bpenetrate\b",
            "\bpenetration\b",
            "\bpenial\b",
            "\bpenile\b",
            "\bpenis\b",
            "\bpenisbanger\b",
            "\bpenisfucker\b",
            "\bpenispuffer\b",
            "\bperversion\b",
            "\bphallic\b",
            "\bphone sex\b",
            "\bphonesex\b",
            "\bphuck\b",
            "\bphuk\b",
            "\bphuked\b",
            "\bphuking\b",
            "\bphukked\b",
            "\bphukking\b",
            "\bphuks\b",
            "\bphuq\b",
            "\bpiece of shit\b",
            "\bpigfucker\b",
            "\bpikey\b",
            "\bpillowbiter\b",
            "\bpimp\b",
            "\bpimpis\b",
            "\bpinko\b",
            "\bpiss\b",
            "\bpiss off\b",
            "\bpiss pig\b",
            "\bpissed\b",
            "\bpissed off\b",
            "\bpisser\b",
            "\bpissers\b",
            "\bpisses\b",
            "\bpissflaps\b",
            "\bpiss flaps\b",
            "\bpissin\b",
            "\bpissing\b",
            "\bpissoff\b",
            "\bpiss-off\b",
            "\bpisspig\b",
            "\bplayboy\b",
            "\bpleasure chest\b",
            "\bpolack\b",
            "\bpole smoker\b",
            "\bpolesmoker\b",
            "\bpollock\b",
            "\bponyplay\b",
            "\bpoof\b",
            "\bpoon\b",
            "\bpoonani\b",
            "\bpoonany\b",
            "\bpoontang\b",
            "\bpoop\b",
            "\bpoop chute\b",
            "\bpoopchute\b",
            "\bPoopuncher\b",
            "\bporch monkey\b",
            "\bporchmonkey\b",
            "\bporn\b",
            "\bporno\b",
            "\bpornography\b",
            "\bpornos\b",
            "\bpotty\b",
            "\bprick\b",
            "\bpricks\b",
            "\bprickteaser\b",
            "\bprig\b",
            "\bprince albert piercing\b",
            "\bprod\b",
            "\bpron\b",
            "\bprone bone\b",
            "\bpronebone\b",
            "\bprone-bone\b",
            "\bprostitute\b",
            "\bprude\b",
            "\bpsycho\b",
            "\bpthc\b",
            "\bpube\b",
            "\bpubes\b",
            "\bpubic\b",
            "\bpubis\b",
            "\bpunani\b",
            "\bpunanny\b",
            "\bpunany\b",
            "\bpunkass\b",
            "\bpunky\b",
            "\bpunta\b",
            "\bpuss\b",
            "\bpusse\b",
            "\bpussi\b",
            "\bpussies\b",
            "\bpussy\b",
            "\bpussy fart\b",
            "\bpussy palace\b",
            "\bpussylicking\b",
            "\bpussypounder\b",
            "\bpussys\b",
            "\bpust\b",
            "\bputo\b",
            "\bqueaf\b",
            "\bqueef\b",
            "\bqueer\b",
            "\bqueerbait\b",
            "\bqueerhole\b",
            "\bqueero\b",
            "\bqueers\b",
            "\bquicky\b",
            "\bquim\b",
            "\bracy\b",
            "\braghead\b",
            "\braging boner\b",
            "\brape\b",
            "\braped\b",
            "\braper\b",
            "\brapey\b",
            "\braping\b",
            "\brapist\b",
            "\braunch\b",
            "\brectal\b",
            "\brectum\b",
            "\brectus\b",
            "\breefer\b",
            "\breetard\b",
            "\breich\b",
            "\brenob\b",
            "\bretard\b",
            "\bretarded\b",
            "\breverse cowgirl\b",
            "\brevue\b",
            "\brimjaw\b",
            "\brimjob\b",
            "\brimming\b",
            "\britard\b",
            "\brosy palm\b",
            "\brosy palm and her 5 sisters\b",
            "\brtard\b",
            "\br-tard\b",
            "\brubbish\b",
            "\brum\b",
            "\brump\b",
            "\brumprammer\b",
            "\bruski\b",
            "\brusty trombone\b",
            "\bs&m\b",
            "\bs.h.i.t.\b",
            "\bs.o.b.\b",
            "\bs_h_i_t\b",
            "\bs0b\b",
            "\bsadism\b",
            "\bsadist\b",
            "\bsambo\b",
            "\bsand nigger\b",
            "\bsandbar\b",
            "\bSandler\b",
            "\bsandnigger\b",
            "\bsanger\b",
            "\bsantorum\b",
            "\bsausage queen\b",
            "\bscag\b",
            "\bscantily\b",
            "\bscat\b",
            "\bschizo\b",
            "\bschlong\b",
            "\bscissoring\b",
            "\bscrew\b",
            "\bscrewed\b",
            "\bscrewing\b",
            "\bscroat\b",
            "\bscrog\b",
            "\bscrot\b",
            "\bscrote\b",
            "\bscrotum\b",
            "\bscrud\b",
            "\bscum\b",
            "\bseaman\b",
            "\bseduce\b",
            "\bseks\b",
            "\bsemen\b",
            "\bsex\b",
            "\bsexo\b",
            "\bsexual\b",
            "\bsexy\b",
            "\bsh!+\b",
            "\bsh!t\b",
            "\bsh1t\b",
            "\bs-h-1-t\b",
            "\bshag\b",
            "\bshagger\b",
            "\bshaggin\b",
            "\bshagging\b",
            "\bshamedame\b",
            "\bshaved beaver\b",
            "\bshaved pussy\b",
            "\bshemale\b",
            "\bshi+\b",
            "\bshibari\b",
            "\bshirt lifter\b",
            "\bshit\b",
            "\bs-h-i-t\b",
            "\bshit ass\b",
            "\bshit fucker\b",
            "\bshitass\b",
            "\bshitbag\b",
            "\bshitbagger\b",
            "\bshitblimp\b",
            "\bshitbrains\b",
            "\bshitbreath\b",
            "\bshitcanned\b",
            "\bshitcunt\b",
            "\bshitdick\b",
            "\bshite\b",
            "\bshiteater\b",
            "\bshited\b",
            "\bshitey\b",
            "\bshitface\b",
            "\bshitfaced\b",
            "\bshitfuck\b",
            "\bshitfull\b",
            "\bshithead\b",
            "\bshitheads\b",
            "\bshithole\b",
            "\bshithouse\b",
            "\bshiting\b",
            "\bshitings\b",
            "\bshits\b",
            "\bshitspitter\b",
            "\bshitstain\b",
            "\bshitt\b",
            "\bshitted\b",
            "\bshitter\b",
            "\bshitters\b",
            "\bshittier\b",
            "\bshittiest\b",
            "\bshitting\b",
            "\bshittings\b",
            "\bshitty\b",
            "\bshiz\b",
            "\bshiznit\b",
            "\bshota\b",
            "\bshrimping\b",
            "\bsissy\b",
            "\bskag\b",
            "\bskank\b",
            "\bskeet\b",
            "\bskullfuck\b",
            "\bslag\b",
            "\bslanteye\b",
            "\bslave\b",
            "\bsleaze\b",
            "\bsleazy\b",
            "\bslope\b",
            "\bslut\b",
            "\bslut bucket\b",
            "\bslutbag\b",
            "\bslutdumper\b",
            "\bslutkiss\b",
            "\bsluts\b",
            "\bsmartass\b",
            "\bsmartasses\b",
            "\bsmeg\b",
            "\bsmegma\b",
            "\bsmut\b",
            "\bsmutty\b",
            "\bsnatch\b",
            "\bsniper\b",
            "\bsnowballing\b",
            "\bsnuff\b",
            "\bs-o-b\b",
            "\bsod off\b",
            "\bsodom\b",
            "\bsodomize\b",
            "\bsodomy\b",
            "\bson of a bitch\b",
            "\bson of a motherless goat\b",
            "\bson of a whore\b",
            "\bson-of-a-bitch\b",
            "\bsouse\b",
            "\bsoused\b",
            "\bspac\b",
            "\bspade\b",
            "\bsperm\b",
            "\bspic\b",
            "\bspick\b",
            "\bspik\b",
            "\bspiks\b",
            "\bsplooge\b",
            "\bsplooge moose\b",
            "\bspooge\b",
            "\bspook\b",
            "\bspread legs\b",
            "\bspunk\b",
            "\bstfu\b",
            "\bstiffy\b",
            "\bstoned\b",
            "\bstrap on\b",
            "\bstrapon\b",
            "\bstrappado\b",
            "\bstrip\b",
            "\bstrip club\b",
            "\bstroke\b",
            "\bstupid\b",
            "\bstyle doggy\b",
            "\bsuck\b",
            "\bsuckass\b",
            "\bsucked\b",
            "\bsucking\b",
            "\bsucks\b",
            "\bsuicide girls\b",
            "\bsultry women\b",
            "\bsumofabiatch\b",
            "\bswastikav\b",
            "\bswinger\b",
            "\bt1t\b",
            "\bt1tt1e5\b",
            "\bt1tties\b",
            "\btaff\b",
            "\btaig\b",
            "\btainted love\b",
            "\btaking the piss\b",
            "\btampon\b",
            "\btard\b",
            "\btart\b",
            "\btaste my\b",
            "\btawdry\b",
            "\btea bagging\b",
            "\bteabagging\b",
            "\bteat\b",
            "\bteets\b",
            "\bteez\b",
            "\bteste\b",
            "\btestee\b",
            "\btestes\b",
            "\btestical\b",
            "\btesticle\b",
            "\btestis\b",
            "\bthreesome\b",
            "\bthroating\b",
            "\bthrust\b",
            "\bthug\b",
            "\bthundercunt\b",
            "\bthunder cunt\b",
            "\btied up\b",
            "\btight white\b",
            "\btinkle\b",
            "\btit\b",
            "\btit wank\b",
            "\btitfuck\b",
            "\btiti\b",
            "\btities\b",
            "\btits\b",
            "\btitt\b",
            "\btittie5\b",
            "\btittiefucker\b",
            "\btitties\b",
            "\btitty\b",
            "\btittyfuck\b",
            "\btittyfucker\b",
            "\btittywank\b",
            "\btitwank\b",
            "\btoke\b",
            "\btongue in a\b",
            "\btoots\b",
            "\btopless\b",
            "\btosser\b",
            "\btowelhead\b",
            "\btramp\b",
            "\btranny\b",
            "\btrashy\b",
            "\btribadism\b",
            "\btrumped\b",
            "\btub girl\b",
            "\btubgirl\b",
            "\bturd\b",
            "\btush\b",
            "\btushy\b",
            "\btw4t\b",
            "\btwat\b",
            "\btwathead\b",
            "\btwatlips\b",
            "\btwats\b",
            "\btwatty\b",
            "\btwatting\b",
            "\btwatwaffle\b",
            "\btwink\b",
            "\btwinkie\b",
            "\btwo fingers\b",
            "\btwo fingers with tongue\b",
            "\btwo girls 1 cup\b",
            "\btwo girls one cup\b",
            "\btwunt\b",
            "\btwunter\b",
            "\bugly\b",
            "\bunclefucker\b",
            "\bundies\b",
            "\bundressing\b",
            "\bunwed\b",
            "\bupskirt\b",
            "\burethra play\b",
            "\burinal\b",
            "\burine\b",
            "\burophilia\b",
            "\buterus\b",
            "\buzi\b",
            "\bv14gra\b",
            "\bv1gra\b",
            "\bvag\b",
            "\bvagina\b",
            "\bvajayjay\b",
            "\bva-j-j\b",
            "\bvalium\b",
            "\bvenus mound\b",
            "\bveqtable\b",
            "\bviagra\b",
            "\bvibrator\b",
            "\bviolet wand\b",
            "\bvirgin\b",
            "\bvixen\b",
            "\bvjayjay\b",
            "\bvodka\b",
            "\bvomit\b",
            "\bvorarephilia\b",
            "\bvoyeur\b",
            "\bvulgar\b",
            "\bvulva\b",
            "\bw00se\b",
            "\bwad\b",
            "\bwang\b",
            "\bwank\b",
            "\bwanker\b",
            "\bwankjob\b",
            "\bwanky\b",
            "\bwazoo\b",
            "\bwedgie\b",
            "\bweed\b",
            "\bweenie\b",
            "\bweewee\b",
            "\bweiner\b",
            "\bweirdo\b",
            "\bwench\b",
            "\bwet dream\b",
            "\bwetback\b",
            "\bwh0re\b",
            "\bwh0reface\b",
            "\bwhite power\b",
            "\bwhiz\b",
            "\bwhoar\b",
            "\bwhoralicious\b",
            "\bwhore\b",
            "\bwhorealicious\b",
            "\bwhorebag\b",
            "\bwhored\b",
            "\bwhoreface\b",
            "\bwhorehopper\b",
            "\bwhorehouse\b",
            "\bwhores\b",
            "\bwhoring\b",
            "\bwigger\b",
            "\bwillies\b",
            "\bwilly\b",
            "\bwindow licker\b",
            "\bwiseass\b",
            "\bwiseasses\b",
            "\bwog\b",
            "\bwomb\b",
            "\bwop\b",
            "\bwrapping men\b",
            "\bwrinkled starfish\b",
            "\bxrated\b",
            "\bx-rated\b",
            "\bxx\b",
            "\bxxx\b",
            "\byaoi\b",
            "\byeasty\b",
            "\byellow showers\b",
            "\byid\b",
            "\byiffy\b",
            "\byobbo\b",
            "\bzibbi\b",
            "\bzoophilia\b",
            "\bzubb\b",

            "\bжид(у|ам|)\b",
            "\bпутин\b",
            "\bтвоюмать\b",
            "\bсмерть$\b",
            "\bфаш(ик|ист|из)\b",
            "\bвойне$\b",
            "\bчушпан$\b",
            "\bукраин.*\b",
            "\bбл(я|уа|и)(д|т)\b",
            "\bбл(я|уа)\b",
            "\bвл(я|уа)\b",
            "\bн(е|и)г(е|)р\b",
            "\bгей\b",
            "\bгомик\b",
            "\bанус$\b",
            "\bчлен$\b",
            "\bуретра$\b",
            "\bдавалка\b",
            "\bрукоблуд\b",
            "\bссанина\b",
            "\bочко$\b",
            "\bпилотка$\b",
            "\bвагина\b",
            "\bвлагалище\b",
            "\bдроч(|ь|ила)\b",
            "\bмошонка$\b",
            "\bелда$\b",
            "\bпердун\b",
            "\bпутана\b",
            "\bг(о|а)ловка\b",
            "\bблев\b",
            "\bг(о|а)в(е|)н\b",
            "\bжоп\b",
            "\b(о|а)н(о|а)нист.*\b",
            "\bгнид(а|о|у|ы)\b",
            "\bк(а|о)злина$\b",
            "\bк(о|а)зел$\b",
            "\bк(о|а)за$\b",
            "\bсволоч(ь|ъ|и|уга|ам|ами).*\b",
            "\bлошар.*\b",
            "\bло(х|шок)$\b",
            "\bлох[уеыаоэяию].*\b",
            "\b.*урод(ы|у|ам|ина|ины).*\b",
            "\b.*бля(т|д).*\b",
            "\b.*гандо.*\b",
            "\bм(а|о)нд(а|о).*\b",
            "\bмуда(к|ч)\b",
            "\b.*сперма.*\b",
            "\bуеб(ан|ок)\b",
            "\bуебищ\b",
            "\b.*[уеыаоэяию]еб$\b",
            "\bсуч(к|)(а|у|и|е|ой|ай).*\b",
            "\bпридур(ок|ки).*\b",
            "\bд(е|и)би(л|лы).*\b",
            "\bсос(ать|и|ешь|у)$\b",
            "\bзалуп.*\b",
            "\bкака$\b",
            "\bкака(ш|х)\b",
            "\bнаци(ст|к|з)$\b",
            "\bмоча$\b",
            "\bмуд(е|ил|о|а|я|еб).*\b",
            "\b.*шалав(а|ы|ам|е|ами).*\b",
            "\b.*пр(а|о)ст(и|е)т(у|е)тк(а|и|ам|е|ами).*\b",
            "\b.*шлюх(а|и|ам|е|ами).*\b",
            "\b.*(х)у(й|и|ю|я|е|л(и|е)).*\b",
            "\b.*п(и|е|ы|у)зд.*\b",
            "\bпенис\b",
            "\bпис(ю|я|ьк|ос)\b",
            "\b.*попа$\b",
            "\b(с|сц)ук(а|о|и|у).*\b",
            "\bсись\b",
            "\bублюд(к|ок)\b",
            "\bеб\\w*\b",
            "\b.*(д(о|а)лб(о|а)|разъ|разь|за|вы|по)ебы*.*\b",
            "\b.*п(и|е)д(а|о|е|)р.*\b",
            "\b.*хер.*\b",
            "\bхрен\b",
            "\bуби(й|в|т|л)\b",
            "\bуб(о|е)й\b",
            "\bкуси оча$\b",
            "\bкус$\b",
            "\bкер$\b",
            "\bкуни ота$\b",
            "\bбева$\b",
            "\bканчик$\b",
            "\bкун$\b",
            "\bдалбен$\b",
            "\bбуз$\b",
            "\bгов$\b",
            "\bчалаб$\b",
            "\bкуслес$\b",
            "\bаблах$\b",
            "\bкунте$\b",
            "\bкунти$\b",
            "\bкул$\b",
            "\bкыл$\b",
            "\bкудаки рих$\b",
            "\bкуси биби$\b",
            "\bкери бобо$\b",
            "\bсиях$\b",
            "\bсаг$\b",
        };
    }
}
